# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0002_auto_20180911_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.OneToOneField(on_delete=models.SET('deleted'), to='relapp.Student'),
        ),
    ]
