# Generated by Django 2.1 on 2018-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='sample@gamil.com', max_length=20),
        ),
    ]
