# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.OneToOneField(null=True, on_delete=models.SET(4), to='myapp.Student'),
        ),
    ]
