# Generated by Django 2.1 on 2018-09-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sproxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('myapp.student',),
        ),
    ]
