# Generated by Django 2.1 on 2018-09-25 09:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
            ],
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Sproxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('myapp.std',),
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
