# Generated by Django 2.1 on 2018-09-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='loc',
            field=models.CharField(max_length=20),
        ),
    ]
