# Generated by Django 2.1 on 2018-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('sal', models.IntegerField()),
            ],
            options={
                'ordering': ['sal'],
            },
        ),
    ]
