# Generated by Django 2.1 on 2018-09-25 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180925_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Emp')),
            ],
        ),
    ]
