# Generated by Django 2.1 on 2018-10-17 05:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=20)),
                ('productCost', models.IntegerField()),
                ('productQuantity', models.IntegerField()),
                ('productDescription', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['productQuantity'],
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['productName'], name='product_product_73b60e_idx'),
        ),
    ]
