# Generated by Django 2.1 on 2018-10-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productAvability',
            field=models.CharField(default='Y', max_length=20),
            preserve_default=False,
        ),
    ]
