# Generated by Django 2.1 on 2018-10-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_product_productavability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productAvability',
        ),
    ]
