# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0004_auto_20180911_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='relapp.Student'),
        ),
    ]
