# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0005_auto_20180911_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='cid',
        ),
    ]
