# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0006_auto_20180911_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relapp.Student'),
        ),
    ]
