# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='depart',
            name='ed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Emp'),
        ),
    ]
