# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180912_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depart',
            name='ed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Emp'),
        ),
    ]
