# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-20 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studet',
            new_name='Student',
        ),
    ]
