# Generated by Django 2.1 on 2018-09-24 17:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emp',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
