# Generated by Django 2.1 on 2019-01-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='country',
        ),
        migrations.RemoveField(
            model_name='info',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='info',
            name='phone',
        ),
    ]
